export const FOCUSED = 'FOCUSED'
export const NOTFOCUSED = 'NOTFOCUSED'

export const HEADER_LIST = 'HEADER_LIST'
export const HEADER_LIST_SUCCESS = 'HEADER_LIST_SUCCESS'

export const MOUSEENTER = 'MOUSEENTER'
export const MOUSELEAVE = 'MOUSELEAVE'

export const CHANGEPAGE = 'CHANGEPAGE'