export const FETCHTOPIC = 'FETCHTOPIC'
export const FETCHTOPIC_SUCCESS = 'FETCHTOPIC_SUCCESS'

export const FETCH_LIST = 'FETCH_LIST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_MORE_LIST = 'FETCH_MORE_LIST'
export const FETCH_MORE_LIST_SUCCESS = 'FETCH_MORE_LIST_SUCCESS'

export const FETCH_WRITER = 'FETCH_WRITER'
export const FETCH_WRITER_SUCCESS = 'FETCH_WRITER_SUCCESS'

export const BACKTOP = 'BACKTOP'